# Generated by Django 4.2 on 2023-06-02 15:36

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields
import web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academy', models.CharField(max_length=32, verbose_name='学院')),
                ('code', models.CharField(max_length=6, verbose_name='学院代码')),
                ('img', models.ImageField(default='academy/default.jpg', upload_to='academy/', verbose_name='图片')),
                ('profile', models.TextField(default='暂无简介', verbose_name='学院简介')),
            ],
            options={
                'verbose_name_plural': '学院',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=32, verbose_name='课程')),
                ('img', models.ImageField(default='course/img/default.jpg', upload_to='course/img/', verbose_name='图片')),
                ('profile', models.TextField(default='暂无简介', verbose_name='课程简介')),
            ],
            options={
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=64, verbose_name='分段名')),
                ('resource_file', web.models.MyFileField(default='course/resource/default.pdf', upload_to='course/resource/', verbose_name='学习资源')),
                ('order', models.SmallIntegerField(default=1, verbose_name='次序')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.course', verbose_name='课程')),
            ],
            options={
                'verbose_name_plural': '课程资源',
            },
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('profile', models.TextField(max_length=128, verbose_name='简介')),
                ('rtf_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='富文本格式内容')),
                ('md_content', mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='Markdown格式内容')),
                ('content_type', models.SmallIntegerField(choices=[(0, '富文本'), (1, 'Markdown')], default=0)),
                ('annex', web.models.MyFileField(blank=True, null=True, upload_to='forum/annex/', verbose_name='附件')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='发贴时间')),
                ('status', models.SmallIntegerField(choices=[(0, '待审核'), (1, '审核通过'), (2, '含有敏感字段'), (3, '退回')], default=0, verbose_name='状态')),
            ],
            options={
                'verbose_name_plural': '论坛',
            },
        ),
        migrations.CreateModel(
            name='ForumImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='forum/img/', verbose_name='图片')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=32, verbose_name='关键词')),
            ],
            options={
                'verbose_name_plural': '关键词',
            },
        ),
        migrations.CreateModel(
            name='SensitiveWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.SmallIntegerField(choices=[(0, '其他'), (1, '色情'), (2, '民生'), (3, '反动'), (4, '贪腐'), (5, '暴恐')], default=0, verbose_name='类别')),
                ('word', models.CharField(max_length=32, verbose_name='敏感词')),
            ],
            options={
                'verbose_name_plural': '敏感词',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32, verbose_name='昵称')),
                ('uname', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('gender', models.SmallIntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('birthday', models.DateField(default='2000-1-1', verbose_name='出生日期')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号码')),
                ('email', models.CharField(blank=True, max_length=64, null=True, verbose_name='邮箱地址')),
                ('head', models.ImageField(default='head/default.jpg', upload_to='head', verbose_name='头像')),
            ],
            options={
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='教师')),
                ('code', models.CharField(default='123456', max_length=64, verbose_name='职工编号')),
                ('professional_title', models.SmallIntegerField(choices=[(0, '讲师'), (1, '副教授'), (2, '教授')], default=0, verbose_name='职称')),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.academy', verbose_name='学院')),
            ],
            options={
                'verbose_name_plural': '教师',
            },
        ),
        migrations.CreateModel(
            name='ForumClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='点击时间')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.forum', verbose_name='帖子')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.user', verbose_name='用户')),
            ],
        ),
        migrations.AddField(
            model_name='forum',
            name='keyword',
            field=models.ManyToManyField(blank=True, to='web.keyword', verbose_name='关键词'),
        ),
        migrations.AddField(
            model_name='forum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.user', verbose_name='用户'),
        ),
        migrations.CreateModel(
            name='CourseResourceTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField(verbose_name='时间')),
                ('course_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.courseresource', verbose_name='课程资源')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.user', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='CourseClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='点击时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.course', verbose_name='课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.user', verbose_name='用户')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='keyword',
            field=models.ManyToManyField(blank=True, to='web.keyword', verbose_name='关键词'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.teacher', verbose_name='教师'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128, verbose_name='评论')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.course', verbose_name='课程')),
                ('forum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.forum', verbose_name='帖子')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.user', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '评论',
            },
        ),
    ]
